# Site settings
title:       Chris Bubernak
email:       chris.bubernak@gmail.com
author:      Chris Bubernak
description: "My blog."
baseurl:     ""
url:         "http://bubernak.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 'bubernak.com'

# Social icons
show_social_icons: true
github_username: chrisbubernak
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
#highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
